ALGORITHM_VERSION = "0.5.10-surface-v9-maximum"
NORMALIZATION_VERSION = "0.2.0"
DECISION_ENGINE_VERSION = "0.1.8"
MODEL_VERSION = "native_surface_verifier_v2+context_meta_v2.1"
AI_CATALOG_VERSION = "0.2.0"

VALIDATOR_VERSION = "0.2.2"

SERIES_ALGORITHM_VERSION = "0.4.0"
